CREATE TABLE IF NOT EXISTS email_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    to_email VARCHAR(255) NOT NULL,

    subject VARCHAR(255) NOT NULL,

    body TEXT NOT NULL,

    status VARCHAR(255) NOT NULL,

    retry_count INTEGER NOT NULL,

    last_error VARCHAR(1000),

    created_at TIMESTAMP NOT NULL,

    last_attempt_at TIMESTAMP
);